package com.btg.commission.enums;

import lombok.Getter;

@Getter
public enum ReminderTodoTypeEnum {

    SETTLEMENT_REVIEW("SETTLEMENT_REVIEW"),
    PROFIT_REPORT_REVIEW("PROFIT_REPORT_REVIEW"),
    SETTLEMENT_PAYABLE("SETTLEMENT_PAYABLE"),
    REPLENISHMENT_ADMIN_REVIEW("REPLENISHMENT_ADMIN_REVIEW"),
    QUALIFICATION_REVIEW("QUALIFICATION_REVIEW"),
    REPLENISHMENT_REPAY_REVIEW("REPLENISHMENT_REPAY_REVIEW"),
    REPLENISHMENT_APPLICANT_CONFIRM("REPLENISHMENT_APPLICANT_CONFIRM"),
    PROFIT_REPORT_RETURNED("PROFIT_REPORT_RETURNED"),
    REPLENISHMENT_RETURNED("REPLENISHMENT_RETURNED"),
    REPLENISHMENT_REPAY_RETURNED("REPLENISHMENT_REPAY_RETURNED"),
    PROFIT_CONFIG_MODE_AUDIT("PROFIT_CONFIG_MODE_AUDIT");

    private final String code;

    ReminderTodoTypeEnum(String code) {
        this.code = code;
    }
}
