CREATE TABLE `btg_todo_reminder` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT '旧字段：接收提醒的用户（兼容）',
  `task_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '旧字段：任务类型（兼容）',
  `related_id` bigint(20) NOT NULL COMMENT '旧字段：相关业务ID（兼容）',
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT '旧字段：PENDING / COMPLETED（兼容）',
  `todo_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '统一待办类型',
  `business_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务域：settlement/profit_report/replenishment/repay/qualification',
  `business_id` bigint(20) NOT NULL COMMENT '业务主键ID',
  `owner_user_id` bigint(20) NOT NULL COMMENT '待办归属用户',
  `reminder_state` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / DONE / CANCELLED',
  `source_status` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '源单状态快照',
  `source_updated_at` datetime DEFAULT NULL COMMENT '源单更新时间快照',
  `dedupe_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等去重键',
  `resolved_at` datetime DEFAULT NULL COMMENT '关闭时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '任务更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_dedupe_state` (`dedupe_key`,`reminder_state`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_owner_open` (`owner_user_id`,`reminder_state`,`todo_type`),
  KEY `idx_business` (`business_type`,`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='待办事项提醒';
